### ISSUE TITLE
When running cron_daily.php It does not remove old meetings from mysql

### ISSUE THREAD

**Issue by snakey85** [andrewwippler/rpi-wayfinding#18]
When we run cron_daily.php we get a couple of warning messages on the apache logs as below:
[Wed Jan 13 11:15:21.040758 2016] [:error] [pid 1101] [client ::1:49049] PHP Warning:  mysqli_stmt_execute() expects parameter 1 to be mysqli_stmt, boolean given in /var/www/html/clean.php on line 16
[Wed Jan 13 11:15:21.041399 2016] [:error] [pid 1101] [client ::1:49049] PHP Warning:  mysqli_stmt_execute() expects parameter 1 to be mysqli_stmt, boolean given in /var/www/html/clean.php on line 22

Once this has run it hasn't seemed to have removed the meetings from the yesterday. If you runt he command on it's own via CLI on mysql then it is fine.

**Comment by andrewwippler** [comment]
What type of host (distribution) is this run on? Is SELinux enabled?

If you `chmod +x clean.php` does it work then?

If you replace line 60 in `cron_daily.php` with the contents of `clean.php`, do the errors go away?

**Comment by snakey85** [comment]
It's running on Raspbian, SELinux isn't installed as default.

When replacing there are still the same errors
[Wed Jan 13 13:40:50.599661 2016] [:error] [pid 1098] [client ::1:49074] PHP Warning:  mysqli_stmt_execute() expects parameter 1 to be mysqli_stmt, boolean given in /var/www/html/cron_daily.php on line 68
[Wed Jan 13 13:40:50.600282 2016] [:error] [pid 1098] [client ::1:49074] PHP Warning:  mysqli_stmt_execute() expects parameter 1 to be mysqli_stmt, boolean given in /var/www/html/cron_daily.php on line 74

**Comment by andrewwippler** [comment]
I have pushed a change to `clean.php` can you revert the changes you made to `cron_daily.php` and insert the new changes into `clean.php`?

What seems to be happening is `$stmt = mysqli_prepare($con, $query)` is returning false rather than an object for `mysqli_stmt_execute($stmt)`.

**Comment by snakey85** [comment]
Thanks it sort of works but still getting an error though this is something different this time?
pi@Room-Test:~ $ curl --silent --compressed http://localhost/cron_daily.php
Table 'rpiwayfinding.rpiwayfinding' doesn't exist

I've just run through the manual install and can't see this table being built maybe there is something i have missed?

**Comment by andrewwippler** [comment]
Try using the last commit - could be that I pushed the wrong table name. I had a
feeling it could be that.

**Comment by snakey85** [comment]
yes this seems to have worked thank you although you still have an sql error
$query2 = "DELETED FROM events WHERE End <= '".date("Y-m-d H:i:s")."'";
instead of 
$query2 = "DELETE FROM events WHERE End <= '".date("Y-m-d H:i:s")."'";

on a slight side note now it's working nicely. (atleast i hope it is the acid test is tomorrow morning)
we seem to be getting alot of notices from exchange.php as below: not sure if this is something to worry about
[Wed Jan 13 17:32:32.678493 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Undefined property: stdClass::$Start in /var/www/html/exchange.php on line 69
[Wed Jan 13 17:32:32.678804 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Undefined property: stdClass::$End in /var/www/html/exchange.php on line 70
[Wed Jan 13 17:32:32.678927 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Undefined property: stdClass::$Subject in /var/www/html/exchange.php on line 71
[Wed Jan 13 17:32:32.679027 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 69
[Wed Jan 13 17:32:32.679134 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 70
[Wed Jan 13 17:32:32.679235 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 71
[Wed Jan 13 17:32:32.679310 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 69
[Wed Jan 13 17:32:32.679410 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 70
[Wed Jan 13 17:32:32.679506 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 71
[Wed Jan 13 17:32:32.679580 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 69
[Wed Jan 13 17:32:32.679677 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 70
[Wed Jan 13 17:32:32.679774 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 71
[Wed Jan 13 17:32:32.679846 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 69
[Wed Jan 13 17:32:32.679944 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 70
[Wed Jan 13 17:32:32.680042 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 71
[Wed Jan 13 17:32:32.680114 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 69
[Wed Jan 13 17:32:32.680211 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 70
[Wed Jan 13 17:32:32.680360 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 71
[Wed Jan 13 17:32:32.680431 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 69
[Wed Jan 13 17:32:32.680527 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 70
[Wed Jan 13 17:32:32.680620 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 71
[Wed Jan 13 17:32:32.680688 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 69
[Wed Jan 13 17:32:32.680781 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 70
[Wed Jan 13 17:32:32.680874 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Trying to get property of non-object in /var/www/html/exchange.php on line 71
[Wed Jan 13 17:32:32.680943 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Undefined property: stdClass::$Start in /var/www/html/exchange.php on line 69
[Wed Jan 13 17:32:32.681039 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Undefined property: stdClass::$End in /var/www/html/exchange.php on line 70
[Wed Jan 13 17:32:32.681134 2016] [:error] [pid 1113] [client ::1:56677] PHP Notice:  Undefined property: stdClass::$Subject in /var/www/html/exchange.php on line 71

**Comment by andrewwippler** [comment]
Comment lines 68-87 of `exchange.php`.

They are basically duplicates of 47-66. My exchange server needed both for some
reason and that is why they are included in the code.

**Comment by snakey85** [comment]
Thank you for this project it works really nice and saved me a lot of time developing myself.
